### ISSUE TITLE
Auto reconnect to socket

### ISSUE THREAD

**Issue by zuidwijk** [svrooij/smartmeter2mqtt#22]
I've been playing with your smartmeter2mqtt and found an issue:

If the connection to a network device get lost, it won't reconnect.

```` YAML
version: "3.7"

services:
  smartmeter:
    image: svrooij/smartmeter:1.6.0-beta.5
    restart: unless-stopped
    ports: # Depending on your situation you'll need to expose some ports
      - 3000:3000
      - 3010:3010
      - 3020:3020
    environment:
      - TZ=Europe/Amsterdam
      - SMARTMETER_socket=192.168.0.10:23
      - SMARTMETER_web-server=3000
      - SMARTMETER_tcp-server=3010
      - SMARTMETER_raw-tcp-server=3020
````

When I disconnect and reconnect my ethernet reader, it won't reconnect.
