### ISSUE TITLE
Home Assistant auto discovery not picked up

### ISSUE THREAD

**Issue by svh1985** [svrooij/smartmeter2mqtt#31]
Hello,

I'm trying to connect the HA, but for some reason HA doesn't pick up the data using auto discovery. I'm not sure what I'm doing wrong. Do I need to add some additional config?

The MQTT messages are published, (filtered view of) MQTT structure:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/5213210/124514215-cace6680-dddc-11eb-9f5b-3541410ac1f3.png">

Docker-Compose

```
  smartmeter:
    container_name: smartmeter
    image: svrooij/smartmeter:beta
    devices:
      - /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AQ4QV4S5-if00-port0:/dev/ttyUSB0
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3010:3010
      - 3020:3020
    environment:
      - TZ=Europe/Amsterdam
      - SMARTMETER_PORT=/dev/ttyUSB0
      - SMARTMETER_web-server=3000
      - SMARTMETER_tcp-server=3010
      - SMARTMETER_raw-tcp-server=3020
      - SMARTMETER_mqtt-url=mqtt://user:pw@172.16.0.1:1883
      - SMARTMETER_mqtt-discovery=true
      - SMARTMETER_debug=true
```

**Comment by svrooij** [comment]
@svh1985 I'm no home assistant user, this auto discovery is build according to the specs (some time ago). Apparently they don't work.

How should the auto discovery messages be formatted? Did you turn on mqtt auto discovery in home assistant?

**Comment by svrooij** [comment]
I've just setup a home assistant instance just to test this.
It seems the discovery message (which is exactly as documented) is not working. Changing them to the same format as zigbee2mqtt and they get picked up immediately.

What values would you like to see in home assistant?

**Comment by svh1985** [comment]
I would like build a dashboard that includes this information:
- Current usage
- Which Tarif (day or night)
- Total day usage & Total night usage
- Maybe optionally overall total usage

Let me know if I can do something to help/test :)

**Comment by svrooij** [comment]
Small sample:

![image](https://user-images.githubusercontent.com/1292510/124655437-201f7c00-dea0-11eb-81a2-c5588794bc00.png)

@svh1985 you could test the latest beta and see if it works for you now, the docker version is currently building, see https://github.com/svrooij/smartmeter2mqtt/runs/3002295741 (usually takes +/- 14 minutes)

**Comment by emontnemery** [comment]
@svrooij 
> It seems the discovery message (which is exactly as documented) is not working. Changing them to the same format as zigbee2mqtt and they get picked up immediately.

Can you give some examples of what you tried which didn't work?

Documentation is here:
- https://www.home-assistant.io/docs/mqtt/discovery/#examples
- https://www.home-assistant.io/integrations/sensor.mqtt/

**Comment by svrooij** [comment]
@emontnemery I didn't see the second page when I implemented this a year ago. After this change the sensors started appearing. Do you need me to write out the config messages or can you see it in the changes?
https://github.com/svrooij/smartmeter2mqtt/commit/d35eb6d4dd51823b1dd0eaf1c1380b242e4813f0#diff-3a9eff3aa76cd9e481d818b422f653ebf166101cc97a5842b684c1caaf555128L104-L118

The object is converted to json before sending to mqtt.

**Comment by svh1985** [comment]
I downloaded the new beta and only the current Tarrif is picked up:

HA
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/5213210/124926544-f1b7b300-dffd-11eb-9ba2-b3f4c636b894.png">

MQTT
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/5213210/124926782-35122180-dffe-11eb-9ed4-bb633451188c.png">

**Comment by emontnemery** [comment]
@svrooij The change makes substantial changes to the functionality though; you now tie the sensors to a device object in Home Assistant but you also remove the `availability` feature, which means the sensors will always appear as available in Home Assistant.
If sensors are not tied to a device, they will show up as orphans under the MQTT integration as well as under entities but not be listed under devices.
Before this change, what went wrong or didn't work as expected?

By the way:
- If you set [`state_class`](https://www.home-assistant.io/integrations/sensor.mqtt/#state_class) to `measurement` for a certain sensor, that sensor will be included in Home Assistant's long term statistics, you probably want to do that for all the sensors.
- For the sensors measuring total consumed and exported energy and gas you also need to set the [`last_reset_topic`](https://www.home-assistant.io/integrations/sensor.mqtt/#last_reset_topic) for them to be included in long term statistics. If the smartmeter energy consumption never resets, you can set the `last_reset_topic` to same as `state_topic` and also declare a `last_reset_value_template` which returns UNIX epoch 0: `{{ "1970-01-01T00:00:00+00:00" }}`

**Comment by svrooij** [comment]
@emontnemery [this](https://github.com/svrooij/smartmeter2mqtt/issues/31#issue-937337499) didn't work. I need to mention, I myself am no home assistant user, so adding home assistant support is just for others to enjoy.

The sensors where not picked up (as stated by @svh1985 ), I then started a clean home assistant installation as a docker container in windows (which just works as opposed to the documentation saying not working). And connected it to my already being used mqtt server. The entities didn't show up. So I guess that can be called not working.

I then just tried to send out the same config file as `zigbee2mqtt` does. 

I don't use this part myself, but want to help others, this (home assistant discovery) is included. If it needs changing please state what should be send instead of the current messages (this is de latest version that is building as we speak).

Power usage:

```json
{
  "availability": [
    {
      "topic": "smartmeter/connected",
      "payload_available": "2"
    }
  ],
  "device": {
    "identifiers": [
      "smartmeter_xxx"
    ],
    "model": "KFM5KAIFA-METER",
    "name": "DSMR power 33137",
    "sw_version": "smartmeter2mqtt (0.0.0-development)"
  },
  "device_class": "power",
  "state_class": "measurement",
  "json_attributes_topic": "smartmeter/status/energy",
  "state_topic": "smartmeter/status/energy",
  "name": "Current power usage",
  "icon": "mdi:transmission-tower",
  "unit_of_measurement": "Watt",
  "value_template": "{{ value_json.calculatedUsage }}",
  "unique_id": "smartmeter_xxx_current-usage"
}
```

With these latest messages, the devices just show up, like here. 🎉 

![image](https://user-images.githubusercontent.com/1292510/124945154-2f243c80-e00e-11eb-90c4-bed835d53f2d.png)

![image](https://user-images.githubusercontent.com/1292510/124945263-48c58400-e00e-11eb-943d-987c8134cf14.png)



Starting home assistant in docker on windows `docker run --init -d --name homeassistant -v /etc/localtime:/etc/localtime:ro -v /mnt/c/Users/my-username/.ha:/config -p 8123:8123 ghcr.io/home-assistant/home-assistant:stable`

**Comment by timongrob** [comment]
Hi, 
was playing around with this one to see if I can use it to move from Domoticz to Home Assistant. Am running into the same issue when using the latest build and want to try the beta version but it gives "# Fatal error in , line 0". Would be great if you could help me with this.

Thanks!

**Comment by timongrob** [comment]
For those running into the same issue: I managed to get it work using smartmeter2mqtt-latest version by adding this to my configuration.yaml:
```
# template for Energy mqtt sensor
template:
  - sensor:
      - name: "Electricity Usage"
        unique_id: "DSMREU01"
        unit_of_measurement: "kWh"
        state: >
          {{ states("sensor.current_power_usage") | float(0) / 1000 }}
        device_class: energy
        state_class: total
      - name: "Electricity Usage T1"
        unique_id: "DSMRTU01"
        unit_of_measurement: "kWh"
        state: >
          {{ states("sensor.total_power_used_t1") | float(0) }}
        device_class: energy
        state_class: total_increasing 
      - name: "Electricity Usage T2"
        unique_id: "DSMRTU02"
        unit_of_measurement: "kWh"
        state: >
          {{ states("sensor.total_power_used_t2") | float(0) }}
        device_class: energy
        state_class: total_increasing
      - name: "Electricity Return T1"
        unique_id: "DSMRTR01"
        unit_of_measurement: "kWh"
        state: >
          {{ states("sensor.total_power_delivered_t1") | float(0) }}
        device_class: energy
        state_class: total 
      - name: "Electricity Return T2"
        unique_id: "DSMRTR02"
        unit_of_measurement: "kWh"
        state: >
          {{ states("sensor.total_power_delivered_t2") | float(0) }}
        device_class: energy
        state_class: total
      - name: "Gas Usage"
        unique_id: "DSMRGU01"
        unit_of_measurement: "m³"
        state: >
          {{ states("sensor.total_gas_usage") | float(0) }}
        device_class: gas
        state_class: total_increasing 
```
